Updated c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -18,4 +18,10 @@ jobs:
       run: sudo apt-get install make gcc g++
 
     - name: Build with Make
-      run: make
+      run: |
+        if [ -f Makefile ]; then
+          make
+        else
+          echo "Makefile not found."
+          exit 1
+        fi
